apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
    - name: api-container
      image: onyeechris/time-api:latest
      ports:
        - containerPort: 3000