name: Frontend CI-CD

on:
  push:
    branches: [ "main" ] 

    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.docker_build.outputs.image }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run build --if-present
    
    - name: Build Docker Image3
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: onyeechris/time-api
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: main-${{ github.sha }}
      
    - name: Set output image tag
      id: set_output
      run: echo "::set-output name=image_tag::main-${{ github.sha }}"



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure gcloud
        run: |
          gcloud config set compute/zone ${{ secrets.GCP_ZONE }}
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }}

      - name: Set IMAGE_TAG environment variable
        run: echo "IMAGE_TAG=main-${{ github.sha }}" >> $GITHUB_ENV
        
      - name: Replace image tag in deployment file
        run: sed -i 's|onyeechris/time-api:latest|onyeechris/time-api:${{ env.IMAGE_TAG }}|' time-api.yaml
      
      - name: Deploy apps
        run: |
          kubectl apply -f time-api.yaml
          kubectl apply -f loadb.yaml

